"""empty message

Revision ID: 27fde7f5e246
Revises: 484f022e2566
Create Date: 2022-06-15 01:13:06.802654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fde7f5e246'
down_revision = '484f022e2566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poped', sa.Column('restaurant', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poped', 'restaurant')
    # ### end Alembic commands ###
