"""empty message

Revision ID: 5c023d285ca4
Revises: 7a96d22536c3
Create Date: 2022-06-10 21:14:17.237008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c023d285ca4'
down_revision = '7a96d22536c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pop', 'pop_restaurant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pop', sa.Column('pop_restaurant_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
