"""empty message

Revision ID: 7926893f7d6e
Revises: 5c023d285ca4
Create Date: 2022-06-10 21:16:02.389878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7926893f7d6e'
down_revision = '5c023d285ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pop', type_='foreignkey')
    op.create_foreign_key(None, 'pop', 'restaurant', ['pop_restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pop', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pop', sa.Column('restaurant_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'pop', type_='foreignkey')
    op.create_foreign_key(None, 'pop', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
