"""empty message

Revision ID: b92d07f5c4a4
Revises: 27fde7f5e246
Create Date: 2022-06-15 11:42:10.459361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92d07f5c4a4'
down_revision = '27fde7f5e246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('detail', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'detail')
    # ### end Alembic commands ###
