"""empty message

Revision ID: dd9b501f1ad3
Revises: 2ffb53b505f5
Create Date: 2022-05-25 14:43:35.680608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9b501f1ad3'
down_revision = '2ffb53b505f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_name'], ['restaurant.restaurant'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked')
    # ### end Alembic commands ###
