"""empty message

Revision ID: f3c8c8abc0c7
Revises: f7f6cad56df7
Create Date: 2022-06-10 21:22:46.088844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c8c8abc0c7'
down_revision = 'f7f6cad56df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pop_restaurant_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
